theme: jekyll-theme-minimal
title: Mehak's CIT Portfolio
description: On this site, you can find the projects and labs I completed in CIT 281! 
<img src="https://i.ibb.co/pbKCnpk/MD.png" width="200px" />
